### ISSUE TITLE
maybe add another streaming provider?

### ISSUE THREAD

**Issue by buttlicker2** [amvstrm/amvstrm#33]

**Comment by NYT92** [comment]
I am currently working on it but since my API depends on Anify's API (Consumet too) source route, sadly the Zoro and 9anime sources will no longer work properly and might return 

```json
{"error":"Sources not found."}
```

![image](https://github.com/amvstrm/amvstrm/assets/53612429/3d43c5f7-3106-4503-aa86-f3b5e4297b86)

I will continue to work with it once the API is stable but I don't think it will :(
